### ISSUE TITLE
你好，即使是使用AndroidKiller 签名后，安装APK依然报错，

### ISSUE THREAD

**Issue by RookieExaminer** [SeagullOddy/android-killer#1]
你好，即使是使用AndroidKiller 签名后，安装APK依然报错，INSTALL_FAILED_INVALID_APK。
使用zipalign对齐APK后，才能安装。有没有办法解决在AndroidKiller 签名后自动对齐呢
最后感谢你的开源。

**Comment by SeagullOddy** [comment]
等有空了我试试哦~

**Comment by RookieExaminer** [comment]
好的好的，感谢

**Comment by SeagullOddy** [comment]
你有没有 INSTALL_FAILED_INVALID_APK 的具体报错信息？或者看看[这篇文章](https://blog.csdn.net/yiran1919/article/details/132760445)里的问题汇总和你情况一不一样呢。

**Comment by SeagullOddy** [comment]
我自己拿滑雪大冒险试了一下发现没有问题😿
